server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # Next.js frontend
            allowedMethods: "*"
            allowedHeaders: "Authorization,Content-Type,Accept-Language,No-Auth"
            allowCredentials: true
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/**
        - id: essay-service
          uri: lb://ESSAY-SERVICE
          predicates:
              - Path=/essay/**
        - id: interaction-service
          uri: lb://INTERACTION-SERVICE
          predicates:
            - Path=/interaction/**

  main:
    web-application-type: reactive

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
    cache-duration: 3600


#logging:
#  level:
#    org.springframework.beans.factory: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
