server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/**
        - id: essay-service
          uri: lb://ESSAY-SERVICE
          predicates:
              - Path=/essay/**

  main:
    web-application-type: reactive

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
    cache-duration: 3600


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
