# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai-service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i-service.proto\x12\x02\x61i\"$\n\x0ePredictRequest\x12\x12\n\ninput_data\x18\x01 \x01(\t\"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2?\n\tAIService\x12\x32\n\x07Predict\x12\x12.ai.PredictRequest\x1a\x13.ai.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=24
  _globals['_PREDICTREQUEST']._serialized_end=60
  _globals['_PREDICTRESPONSE']._serialized_start=62
  _globals['_PREDICTRESPONSE']._serialized_end=95
  _globals['_AISERVICE']._serialized_start=97
  _globals['_AISERVICE']._serialized_end=160
# @@protoc_insertion_point(module_scope)
