# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: essay-service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'essay-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65ssay-service.proto\x12\x02\x61i\"\"\n\x0c\x45ssayRequest\x12\x12\n\nessay_text\x18\x01 \x01(\t\"!\n\rEssayResponse\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x01 \x01(\t2D\n\rEssayAnalysis\x12\x33\n\x0c\x41nalyzeEssay\x12\x10.ai.EssayRequest\x1a\x11.ai.EssayResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'essay_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ESSAYREQUEST']._serialized_start=27
  _globals['_ESSAYREQUEST']._serialized_end=61
  _globals['_ESSAYRESPONSE']._serialized_start=63
  _globals['_ESSAYRESPONSE']._serialized_end=96
  _globals['_ESSAYANALYSIS']._serialized_start=98
  _globals['_ESSAYANALYSIS']._serialized_end=166
# @@protoc_insertion_point(module_scope)
