# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: essay-service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'essay-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65ssay-service.proto\x12\x13\x63om.phat.grpc.essay\":\n\x0eScoringRequest\x12\x14\n\x0c\x65ssay_prompt\x18\x01 \x01(\t\x12\x12\n\nessay_text\x18\x02 \x01(\t\"!\n\x0fScoringResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2d\n\x0c\x45ssayService\x12T\n\x07Scoring\x12#.com.phat.grpc.essay.ScoringRequest\x1a$.com.phat.grpc.essay.ScoringResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'essay_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCORINGREQUEST']._serialized_start=44
  _globals['_SCORINGREQUEST']._serialized_end=102
  _globals['_SCORINGRESPONSE']._serialized_start=104
  _globals['_SCORINGRESPONSE']._serialized_end=137
  _globals['_ESSAYSERVICE']._serialized_start=139
  _globals['_ESSAYSERVICE']._serialized_end=239
# @@protoc_insertion_point(module_scope)
