server:
  port: 10003
  servlet:
    context-path: /interaction

grpc:
  server:
    port: 9084
    negotiationType: plaintext
    enableReflection: true
    maxInboundMessageSize: 104857600 # 100MB
    maxInboundMetadataSize: 1048576 # 1MB
  client:
    essay-service:
      address: static://localhost:9082
      negotiationType: plaintext

    identity-service:
      address: static://localhost:9083
      negotiationType: plaintext

jwt:
  accessSignerKey: ${accessSignerKey}
  refreshSignerKey: ${refreshSignerKey}
  valid-duration: 1800 # in seconds
  refreshable-duration: 2592000 # in seconds

spring:
  config:
    import:
      - "optional:file:env.properties"
      - "optional:file:../env.properties"
  application:
    name: interaction-service
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  data:
    mongodb:
      username: eternity_user
      password: a_will_eternal
      host: localhost
#      uri: mongodb://eternity_user:a_will_eternal@interaction-service-mongodb:27017
      database: interactiondb
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

#logging:
#  level:
#    org.springframework: DEBUG
#_______________________________________API DOCUMENT_______________________________________
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
  show-actuator: true

openapi:
  service:
    api-docs: interaction-service-rest-api
    title: Interaction Service REST API
    description: This is the API documentation for Interaction Service.
    version: 1.0.0
    server-url: http://localhost:${server.port}${server.servlet.context-path}
    server-description: Essay Genius Backend API service For Development

gateway:
  domain: ${GATEWAY_DOMAIN:localhost}
  port: ${GATEWAY_PORT:9000}
